from app.ai.preprocessors.text_cleaner import normalize_arabic_letters

UNAMBIGUOUS_POSITIVE_EMOJIS = {
    "😍",
    "❤️",
    "❤",
    "🔥",
    "👏",
    "😊",
    "👍",
    "🥰",
    "💖",
    "😎",
    "🙏",
    "💪",
    "✨",
    "🎉",
    "😁",
    "😄",
    "😃",
    "🙂",
    "🤩",
    "😘",
    "💕",
    "💯",
    "🌹",
    "🌟",
    "🎊",
    "🎈",
    "🤗",
    "😇",
    "👌",
    "🫶",
    "💙",
    "💚",
    "💛",
    "🧡",
    "💜",
    "🤝",
    "🏆",
    "🥳",
    "🙌",
    "🎀",
    "💐",
    "🌸",
    "🥹",
    "♥️",
    "♥",
    "💗",
    "💓",
    "💞",
    "💘",
}

UNAMBIGUOUS_NEGATIVE_EMOJIS = {
    "😡",
    "🤬",
    "👎",
    "🙄",
    "😒",
    "🤮",
    "😤",
    "😠",
    "🗑️",
    "🤡",
    "😑",
    "☠️",
    "💀",
    "😰",
    "😱",
    "🤢",
    "👺",
    "🚫",
    "❌",
    "⚠️",
}

AMBIVALENT_EMOJIS = {
    "😭",
    "💔",
    "😔",
    "😢",
    "😞",
    "😕",
    "😫",
    "😩",
}

POSITIVE_EMOJIS = UNAMBIGUOUS_POSITIVE_EMOJIS
NEGATIVE_EMOJIS = UNAMBIGUOUS_NEGATIVE_EMOJIS | AMBIVALENT_EMOJIS

SARCASM_EMOJIS = {
    "🙄",
    "😒",
    "😏",
    "🤡",
    "😑",
    "🤦",
    "🤦‍♂️",
    "🤦‍♀️",
}

SARCASM_PHRASES = {
    normalize_arabic_letters(p)
    for p in {
        "يا سلام",
        "واو",
        "عبقري",
        "أكيد",
        "طبعا",
        "ما شاء الله عليك",
        "برافو عليك",
        "روعة يعني",
        "ما أحلى",
        "ولا أروع",
        "أكيد يعني",
        "أقوى شيء شفته",
        "مبدع جدًا",
        "يا للعظمة",
        "تحفة فنية",
        "best thing ever",
        "wow genius",
        "sure bro",
        "great job",
        "amazing quality",
        "perfect as always",
        "جامد أوي كده",
        "فنان يا باشا",
        "هو انت جامد",
        "يا هلا فيك",
        "شو هالعبقرية",
        "ما شاء الله عليك ياخي",
        "الله يعطيك العافية",
    }
}

ENGAGEMENT_PATTERNS = [
    normalize_arabic_letters(p)
    for p in [
        "2024",
        "2025",
        "2026",
        "2027",
        "من يتابع",
        "مين يتابع",
        "من يشاهد",
        "مين يشاهد",
        "من موجود",
        "مين موجود",
        "من هنا",
        "مين هنا",
        "مين متابع من زمان",
        "من متابع من زمان",
        "لسه يتابع",
        "لسا يتابع",
        "لسا موجود",
        "لسه موجود",
        "مين جاي من",
        "من جاي من",
        "مين جاء من",
        "من جاء من",
        "مين يسمع",
        "من يسمع",
        "مين يتذكر",
        "من يتذكر",
        "مين رجع",
        "من رجع",
        "مين حضر",
        "من حضر",
        "مين لسه",
        "من لسه",
        "حد هون",
        "حد هنا",
        "في حد",
        "في احد",
        "مين صاحي",
        "من صاحي",
        "مين يشوف",
        "من يشوف",
        "مين يشاهد في",
        "من يشاهد في",
        "اللي جاى من",
        "الي جاي من",
        "who is watching",
        "anyone watching",
        "still watching",
        "watching in",
        "who is here",
        "anyone here",
        "who came from",
        "who remembers",
        "anyone remember",
        "who's listening",
        "who is listening",
        "who is still listening",
        "still listening",
        "who's still here",
        "watching this in",
        "listening in",
        "anyone in",
        "who else",
        "am i the only one",
        "is anyone else",
        "who is watching this in",
    ]
]
